name: SkyCaveLobby
main: de.leonheuer.skycave.lobby.SkyCaveLobby
version: 1.1.0
authors: [ Hakuyamu ]
api-version: 1.18

commands:
  setspawn:
    permission: skycave.lobby.command.setspawn
  spawn:
    description: spawn command